FROM python:3.10-slim-buster

ENV PYTHONUNBUFFERED 1
ENV MUJOCO_GL egl
ADD ./agent /
ADD ./utils /
ADD requirements/agent_random.txt /
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    cmake \
    libglfw3 libglfw3-dev
RUN pip install --upgrade pip
RUN pip install -r agent_random.txt
CMD [ "python", "agent_maniMPL_random.py" ]
